imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        handler_id:  ~
        storage_id: session.storage.filesystem
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db"

parameters:
    retromat.activity.import.file_names:
        en: "%kernel.root_dir%/../tests/AppBundle/data/activities_en.js"
        de: "%kernel.root_dir%/../tests/AppBundle/data/activities_de.js"
        es: "%kernel.root_dir%/../tests/AppBundle/data/activities_es.js"
        fr: "%kernel.root_dir%/../tests/AppBundle/data/activities_fr.js"
        nl: "%kernel.root_dir%/../tests/AppBundle/data/activities_nl.js"
        ru: "%kernel.root_dir%/../tests/AppBundle/data/activities_ru.js"