parameters:
    # maybe put this into the database later
    retromat.plan.titles:
        sequence_of_groups:
            0:  [  0, 1,    3,    5, 6, 7, 8,    10     ]
            1:  [  0,    2,    4, 5, 6, 7,    9         ]
            2:  [  0, 1,    3,    5, 6, 7, 8,    10     ]
            3:  [  0,    2,    4, 5, 6, 7,    9         ]
            4:  [  0, 1,          5,    7,           11 ]
            5:  [  0, 1,          5,       8,        11 ]
            6:  [  0,    2,       5,    7,           11 ]
            7:  [  0,    2,       5,       8,        11 ]
            8:  [ 12, 1,    3,    5, 6,           10    ]
            9:  [ 12,    2,    4, 5, 6,        9        ]
            10: [ 12, 1,    3,    5, 6,           10    ]
            11: [ 12,    2,    4, 5, 6,        9        ]
            12: [ 13,             5, 6, 7, 8,    10     ]
            13: [ 13,             5, 6, 7,    9         ]
            14: [ 13,             5, 6, 7, 8,    10     ]
            15: [ 13,             5, 6, 7,    9         ]

        groups_of_terms:
            # "" as first element marks the group as optional (may be skipped to satisfy length constraints)
            0:  ["", "Retromat:"]
            1:  ["", "Kanban", "Lean"] # either 1+3 (without iterations) or 2+4 (with iteration)
            2:  ["", "Agile", "Scrum", "XP", "Extreme Programming"]
            3:  ["", "Release", "Project", "Program", "Process", "Team", "Over All"]
            4:  ["", "Release", "Project", "Program", "Process", "Team", "Over All", "Iteration", "Sprint", "Cycle"]
            5:  ["Retrospective", "Retro", "Post Mortem", "A3", "Lessons Learned", "Reflection", "Inspect & Adapt", "Analysis"]
            6:  ["", "Meeting", "Event", "Discussion", "Ceremony"]
            7:  ["", "Plan", "Agenda", "Structure", "Experiment"]
            8:  ["", "Ideas", "Inspiration", "Example"]
            9:  ["", "Activities"] # either 9 or 10
            10: ["", "with 5 Activities", "with 5 Stages", "with 5 Steps", "with 5 Ideas", "with 5 Activity Ideas", "with 5 Activity Examples"]
            11: ["", "Generator", "Tool", "Guide", "Directory"]
            12: ["", "Plan Your", "Organize Your", "Create Your", "Prepare Your"]
            13: ["", "Scrum Master Tools:", "ScrumMaster Toolbox:", "Facilitator's Tools:", "Facilitation Toolbox:"]

        de:
            sequence_of_groups:
                0:  [  0, 1,    3,    5, 6, 7, 8,    10     ]
                1:  [  0,    2,    4, 5, 6, 7,    9         ]
                2:  [  0, 1,    3,    5, 6, 7, 8,    10     ]
                3:  [  0,    2,    4, 5, 6, 7,    9         ]
                4:  [  0, 1,          5,    7,           11 ]
                5:  [  0, 1,          5,       8,        11 ]
                6:  [  0,    2,       5,    7,           11 ]
                7:  [  0,    2,       5,       8,        11 ]
                8:  [ 12, 1,    3,    5, 6,           10    ]
                9:  [ 12,    2,    4, 5, 6,        9        ]
                10: [ 12, 1,    3,    5, 6,           10    ]
                11: [ 12,    2,    4, 5, 6,        9        ]
                12: [ 13,             5, 6, 7, 8,    10     ]
                13: [ 13,             5, 6, 7,    9         ]
                14: [ 13,             5, 6, 7, 8,    10     ]
                15: [ 13,             5, 6, 7,    9         ]

            groups_of_terms:
                0: ["", "Retromat:"]
                1: ["", "Kanban", "Lean"] # entweder 1 + 3 (ohne Iterationen) oder 2 + 4 (mit Iteration)
                2: ["", "Agile", "Scrum", "XP", "Extreme Programmierung"]
                3: ["", "Release", "Projekt", "Programm", "Prozess", "Team", "Über alles"]
                4: ["", "Release", "Projekt", "Programm", "Prozess", "Team", "Über alle", "Iteration", "Sprint", "Cycle"]
                5: ["Retrospektive", "Retro", "Post Mortem", "A3", "Lessons Learned", "Reflexion", "Inspect & Adapt", "Analyse"]
                6: ["", "Treffen", "Ereignis", "Diskussion", "Zeremonie"]
                7: ["", "Plan", "Agenda", "Struktur", "Experiment"]
                8: ["", "Ideen", "Inspiration", "Beispiel"]
                9: ["", "Aktivitäten"] # entweder 9 oder 10
                10: ["", "mit 5 Aktivitäten", "mit 5 Stufen", "mit 5 Schritten", "mit 5 Ideen", "mit 5 Aktivitätsideen", "mit 5 Aktivitätsbeispielen"]
                11: ["", "Generator", "Tool", "Guide", "Directory"]
                12: ["", "Plane deine", "organisiere deine", "Erstelle deine", "Bereite deine vor"]
                13: ["", "Scrum Master Tools:", "ScrumMaster Toolbox:", "Werkzeuge des Moderators:", "Moderatoren Toolbox:"]
                # einsortieren: ["Qualitätszirkel"]