security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: team_dashboard
                always_use_default_target_path: true
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous: true
        dev:
            # disables authentication for assets and the profiler, adapt it according to your needs
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_translator_en
            - ROLE_translator_de
            - ROLE_translator_es
            - ROLE_translator_fr
            - ROLE_translator_nl
            - ROLE_translator_ru
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    access_control:
        - { path: ^/(.+)/register, role: ROLE_ADMIN }
