# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    array_to_object_mapper:
        class: AppBundle\Importer\ArrayToObjectMapper
    retromat.activity_by_phase:
        class: AppBundle\Activity\ActivityByPhase
        arguments: ["@doctrine.orm.entity_manager"]
    retromat.activity_source_expander:
        class: AppBundle\Activity\ActivitySourceExpander
        arguments: ["%retromat.activity.source%"]
    retromat.activity_reader:
        class: AppBundle\Importer\Activity\ActivityReader
        arguments: [~, "%retromat.activity.import.file_names%"]
    retromat.activity_importer:
        class: AppBundle\Importer\Activity\ActivityImporter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@retromat.activity_reader"
            - "@array_to_object_mapper"
            - "@validator"
            - "%retromat.activity.import.languages.whitelist%"
    retromat.color_varation:
        class: AppBundle\Twig\ColorVariation
    retromat.plan.description_renderer:
        class: AppBundle\Plan\DescriptionRenderer
    retromat.plan.plan_id_generator:
        class: AppBundle\Sitemap\PlanIdGenerator
        arguments: ["@retromat.activity_by_phase"]
    retromat.plan.title_chooser:
        class: AppBundle\Plan\TitleChooser
        arguments: ["%retromat.plan.titles%", "@retromat.plan.title_renderer", 60]
    retromat.plan.title_id_generator:
        class: AppBundle\Plan\TitleIdGenerator
        arguments: ["%retromat.plan.titles%"]
    retromat.plan.title_renderer:
        class: AppBundle\Plan\TitleRenderer
        arguments: ["%retromat.plan.titles%"]
    retromat.sitemap.plan_generator:
        class: AppBundle\Sitemap\PlanGenerator
        arguments: ["@router", '@retromat.plan.plan_id_generator']
    retromat.sitemap.populate_subscriber:
        class: AppBundle\EventListener\SitemapPopulateSubscriber
        arguments: ["@router", "@doctrine.orm.entity_manager", "@retromat.sitemap.plan_generator", "@retromat.activity_by_phase"]
        tags: [{name: "kernel.event_subscriber"}]
    retromat.doctrine_cache.redis_connection:
        class: Redis
        calls: [[connect, ["%redis_connection%"]]]
    retromat.doctrine_cache.redis:
        parent: doctrine_cache.abstract.redis
        abstract:  false
        calls: [[setRedis, ['@retromat.doctrine_cache.redis_connection']]]